version: '3'
services:
  traefik-proxy:
    restart: always
    container_name: traefik-proxy
    image: traefik
    networks:
      - traefik-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
networks:
    traefik-proxy:
      external: true
