defaultEntryPoints = ["http", "https"]

[entryPoints]
    [entryPoints.http]
    address = ":80"

# Facultatif, renvoie tout le trafic http vers https.
# [entryPoints.http.redirect]
# entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "votre@email.fr"
storage = "acme.json"
entryPoint = "https"
[acme.httpChallenge]
entryPoint = "http"

#[[acme.domains]]
#   main = "localhost"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true
exposedbydefault = false
